### ISSUE TITLE
Where is the password of Baidu Cloud Disk

### ISSUE THREAD

**Issue by critical88** [seukgcode/MELBench#1]
I don't find the password of Baidu Cloud Disk, could you add it in the README.md ?
another issue is that whether the database of Weibo-MEL is Wikidata Knowledge Graph

**Comment by HenryHZY** [comment]
@yyq63728198 Maybe you just missed the password in the README.md. 
"The extraction codes are 2021."

**Comment by critical88** [comment]
Thank you a lot, I missed it, how about another issue "whether the database of Weibo-MEL is Wikidata Knowledge Graph"
