### ISSUE TITLE
RichpediaMEL里每条数据的图片怎么找？

### ISSUE THREAD

**Issue by TideDra** [seukgcode/MELBench#4]
您好，我是汪老师的学生。RichpediaMEL里每条数据并未给出实体对应的图片名或者路径，从网盘下载图片也未能从图片名中看出端倪，请问实体与图片之间是怎么对应的？

**Comment by coreeey** [comment]
同问

**Comment by TideDra** [comment]
The matching between texts and images of raw Richpedia-MEL dataset has been lost. Researchers can use our new bigger Richpedia-MEL dataset in https://github.com/seukgcode/MEL-GHMFC/tree/main/datasets
